# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np # importing Numpy library with a nickname (np)

**2. Print the numpy version and the configuration**

In [4]:
print(np.__version__)
print(np.show_config())

1.19.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ahmad/anaconda3/envs/ensf592\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

**3. Create a 1D array of zeros of size 10 of type float32**

In [5]:
array_1d = np.zeros( (10), dtype='float32' )
print(array_1d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [6]:
Z = np.zeros((32,12))
# Include your solution below
print(Z.size)

384


**5. Create a 1D array with values ranging from 10 to 58**

In [8]:
array_seq = np.arange(10,59)
print(array_seq)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [9]:
a = np.arange(10)
# Include your solution below
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
array_2d = np.arange(9).reshape(3,3)
print(array_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [11]:
id_matrix = np.identity(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [12]:
Z = np.random.random((10,11))
# Include your solution below
print(Z)

[[0.70061646 0.07216889 0.12531365 0.0406739  0.0524111  0.90252353
  0.74049845 0.66094061 0.03999231 0.5449507  0.73507519]
 [0.38830606 0.5598308  0.18237229 0.27999951 0.56337759 0.55748209
  0.91097911 0.2055611  0.90459349 0.39466216 0.63799824]
 [0.77807664 0.22103144 0.49423895 0.36219319 0.32076943 0.37213517
  0.9941862  0.86503755 0.24736775 0.81372469 0.86913537]
 [0.34769535 0.49152652 0.05321214 0.10440516 0.92247876 0.96554604
  0.53729435 0.61276917 0.73509014 0.75397738 0.14141867]
 [0.3509165  0.58575833 0.00837341 0.05374232 0.05206893 0.44078133
  0.96570753 0.40324971 0.92741067 0.35731437 0.94420216]
 [0.13038943 0.33982294 0.82804171 0.60737932 0.89248819 0.41428645
  0.38269826 0.1959673  0.33274791 0.84312489 0.29244149]
 [0.57157984 0.08069701 0.30204915 0.65543492 0.28602313 0.72991449
  0.03054    0.876767   0.769822   0.92658332 0.28260307]
 [0.66521043 0.59270731 0.84822493 0.2915102  0.62830053 0.19891619
  0.46761312 0.48590998 0.91135323 0.56348343 0.94

In [13]:
max = Z.max(axis = 0)
print(max)

[0.77807664 0.90486984 0.87058771 0.65543492 0.92247876 0.96554604
 0.9941862  0.876767   0.92741067 0.92658332 0.94921492]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [15]:
x = np.ones((7,7))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [18]:
Z = np.ones((5,5))
# Include your solution below
paded = np.pad(Z, 1)
print(paded)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [21]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z.astype(int))

[3.26787279 9.02827368 5.08763357 5.74849202 0.09994792 6.09741648
 2.23840341 3.5418442  2.43233152 0.15666682]
[3 9 5 5 0 6 2 3 2 0]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [38]:
matrix_5 = np.zeros((5,5))
matrix_5 += np.arange(5)
matrix_5T = matrix_5.T
print(matrix_5T)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [48]:
print(np.linspace( 0.1, 1, 10, endpoint=False )) 

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


**15. Create a random vector of size 10 and sort it**

In [58]:
vec = np.random.random(10)
vec_sorted = np.sort(vec) 
print(vec_sorted)

[0.14487084 0.18617229 0.27166609 0.28372276 0.30078108 0.44683134
 0.45662648 0.75875165 0.79358783 0.83727098]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [64]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.91860423 0.45387172 0.86137056 0.57592443 0.92666557 1.11049425
 0.98276212 1.14643273 1.0432122  0.46451809]
[0.92102989 0.71850282 0.79677179 1.1153486  0.80398108 0.51238649
 1.33262544 0.57955287 0.30301796 0.87139704]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [67]:
vec = np.random.random(10)
vec[vec.argmax()] = 0
print(vec)

[0.15544367 0.10206428 0.85050482 0.45882768 0.58692606 0.91933143
 0.         0.01292345 0.6048768  0.855473  ]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [73]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
absolute_val_array = np.abs(Z - z)
print(Z[absolute_val_array.argmin()])

0.5324387887497309


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [83]:
#Comment
Z = np.linspace(1, 5, 5)[::-1]
print(Z)
# Include your solution below
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[5. 4. 3. 2. 1.]
[5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [86]:
#Comment
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [87]:
#Comment
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [93]:
def bbox(img):
    #include your solution below
    a = np.where(img != 0)
    r1,r2,c1,c2 = np.min(a[0]), np.max(a[0]), np.min(a[1]), np.max(a[1])
    return (r1,c1),(r2,c2)

from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [7]:
#comment - Not finished
def moving_average(x,N = 3):
    res = [np.sum(x[i:i+N]) for i in range(0, len(x), N)]
    return np.array(res) / N

a = np.arange(30)
print(a)
N = 3
print(moving_average(a,N))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [3]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

[0 2 1 1 2 0 1]


**25. Find the most frequent value in the array below?**

In [115]:
#comment
Z = np.random.randint(0,10,50)
# Include your solution below
print(np.bincount(Z).argmax())

[3 3 4 9 0 0 9 1 0 5 9 7 5 7 1 7 1 1 7 5 2 4 2 3 2 7 2 5 2 1 9 7 7 7 0 9 4
 9 9 0 2 2 9 2 7 5 5 3 5 3]
[5 5 8 5 3 7 0 9 0 8]
7


**26. Write a function to sum_arrurn the n largest values of an array** 

In [125]:
def nlargest(a,n = 5):
    # Include your solution here
    #a = np.sort(a)
    #sum = np.sum(a[-n:])
    ind = np.argpartition(a, -n)[-n:]
    return np.sum(a[ind])
    #return sum

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

49985
